### ISSUE TITLE
File name too long err

### ISSUE THREAD

**Issue by ramonsuarez** [mdb/wp2middleman#30]
Hello, 

I just installed wp2middleman and tried to import an old blog, but I run into this problem: 

```
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/wp2middleman-0.0.3/lib/wp2middleman/migrator.rb:18:in `write': File name too long @ rb_sysopen - /home/ramon/code/ramonsuarez/bbmm/export/2006-12-13-Menos-mal-que-la-economa-va-bien-un-estudio-revela-que-el-salario-medio-de-los-espaoles-no-ha-variado-desde-1997-corta-pega.html.markdown (Errno::ENAMETOOLONG)
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/wp2middleman-0.0.3/lib/wp2middleman/migrator.rb:18:in `block in migrate'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/wp2middleman-0.0.3/lib/wp2middleman/post_collection.rb:17:in `each'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/wp2middleman-0.0.3/lib/wp2middleman/post_collection.rb:17:in `each'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/wp2middleman-0.0.3/lib/wp2middleman/migrator.rb:17:in `migrate'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/wp2middleman-0.0.3/lib/wp2middleman.rb:14:in `migrate'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/wp2middleman-0.0.3/lib/wp2middleman/cli.rb:20:in `wp2mm'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/wp2middleman-0.0.3/bin/wp2mm:9:in `<top (required)>'
	from /usr/local/opt/rbenv/versions/2.3.1/bin/wp2mm:23:in `load'
	from /usr/local/opt/rbenv/versions/2.3.1/bin/wp2mm:23:in `<main>'
```

I've not been able to find information on anny option that would rename these files. How should I do? 

Thanks

**Comment by ramonsuarez** [comment]
Sorry Mike, I figured the problem. I just had to edit the xml file and shorten the long url everywhere. It is not a problem to do a redirect afterwards. 

Thanks for the tool!

**Comment by mdb** [comment]
@ramonsuarez No problem at all. I started on attempting to reproduce, though it sounds like you're happy with the workaround you found. Thanks!
